services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
  web:
    image: apprun-laravel:latest
    environment:
        - APP_ENV=production
    ports:
      - "8080:80"
